name = "alnetbot"
main = "./index1.js"
compatibility_date = "2024-03-04"
[placement]
mode = "smart"
[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "BOT_STORAGE"
id = "487bdf90873f4a25b44c0b62eec39762"
